spring.application.name=sb-ecom

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=Dinesh999@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

                #SQL Database
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
#spring.datasource.username=root
#spring.datasource.password=Dinesh999@
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

project.image=images/

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.app.jwtSecret=mySecretKey123912738asdgrddsdfwkjhferewutuouvmndfhjd
spring.app.jwtExpirationMs=30000000
spring.ecom.app.jwtCookieName=springBootEcom

logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.project=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE